### ISSUE TITLE
Need Focused Form Field Styles

### ISSUE THREAD

**Issue by CITguy** [rackerlabs/encore-ui#1005]
With the current prototype (http://output.jsbin.com/bumibi/36) of rxForm rework, I noticed that there are no visual style for focused form fields.  I made an attempt at applying some visual styles using the CSS `box-shadow` property (http://output.jsbin.com/bumibi/37), but these styles require feedback before being implemented in new rxForm stuff.  *(This is likely something that will be implemented after #884 is complete.)*

**Comment by megalord** [comment]
Got curious so I looked up the browser defaults for Chrome.  For reference:
```css
input:focus {
  outline: -webkit-focus-ring-color auto 5px;
  outline-offset: -2px;
}
```
