### ISSUE TITLE
Discuss design of <code> in docs

### ISSUE THREAD

**Issue by CITguy** [rackerlabs/encore-ui#940]
Current styles in the docs make it difficult to differentiate `<code>` text and normal text. Let's discuss how we can visually differentiate the two.

@glynnis @ElementE @parlarjb @TheNando

**Comment by CITguy** [comment]
I wouldn't be opposed to something like the following.
![screen shot 2015-05-08 at 10 35 39 am](https://cloud.githubusercontent.com/assets/545605/7540431/54108eb8-f573-11e4-8763-34fb5ed57fc9.png)

It shows inline (`<code>...</code>`) and block code examples (`<pre><code>...</code></pre>`)

**Comment by CITguy** [comment]
BTW,

```css
pre, code {
  color: #db7820;
}
pre {
  background-color: #F0F0F0;
  padding: 4px;
  border: 1px solid #CCC;
  border-radius: 2px;
}
```
